### ISSUE TITLE
code doesn't work

### ISSUE THREAD

**Issue by 3wiida** [SparkShen02/Naive-Bayes-Digit-Recognition#1]
it give me this error when trying to run it can you help?
![Screenshot_1](https://github.com/SparkShen02/Naive-Bayes-Digit-Recognition/assets/84087861/f1945e17-63e7-4eaa-ac00-0d51b980dc86)

**Comment by urfavsaka1** [comment]
it happens with me too pls help

**Comment by SS-YS** [comment]
Thanks for pointing it out. Seems like the data file format was slightly changed. Should be solved now.

**Comment by 3wiida** [comment]
thank you
